=== limyandi/TutorBooking/web/WEB-INF/students.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
 xmlns:xs="http://www.w3.org/2001/XMLSchema"
 targetNamespace="http://www.uts.edu.au/31284/wsd-students"
 xmlns="http://www.uts.edu.au/31284/wsd-students"
 elementFormDefault="qualified">
    
    <xs:simpleType name="name">
        <xs:restriction base="xs:string">
            <xs:pattern value="([A-Za-z]{4})"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="email">
        <xs:restriction base="xs:string">
            <xs:pattern value="([A-Za-z\._]+)@(([a-z-]+)\.)+([a-z-]+)"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- Any alphanumeric characters and included some wild symbols with a minimum length of 6 and maximum length of 16.  -->
    <xs:simpleType name="password">
        <xs:restriction base="xs:string">
            <xs:pattern value="([A-Za-z0-9!@#$%^*\?]{6,16})"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="dob">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{1,2}/\d{1,2}/\d{1,4}"/>
        </xs:restriction>
    </xs:simpleType>
    
    
    <!--TODO: DO WE NEED FOR USERTYPE? -->
    <xs:simpleType name="usertype">
        <xs:restriction base="xs:string">
            <xs:pattern value="student"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:element name="students">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="firstname" type="name"/>
                            <xs:element name="lastname" type="name"/>
                            <xs:element name="email" type="email"/>
                            <xs:element name="password" type="password"/>
                            <xs:element name="dateofbirth" type="dob"/>
                            <xs:element name="usertype" type="usertype"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== limyandi/TutorBooking/web/WEB-INF/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="students.xsl"?>
<students xmlns="http://www.uts.edu.au/31284/wsd-students"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.uts.edu.au/31284/wsd-students students.xsd">
    <student>
        <firstname>Rico</firstname>
        <lastname>Vico</lastname>
        <email>rico@gmail.com</email>
        <password>123456</password>
        <dateofbirth>1998-09-09</dateofbirth>
        <usertype>student</usertype>
    </student>
    <student>
        <firstname>Jason</firstname>
        <lastname>Goh</lastname>
        <email>jason@gmail.com</email>
        <password>Digdasd@</password>
        <dateofbirth>1997-10-02</dateofbirth>
        <usertype>student</usertype>
    </student>
    <student>
        <firstname>Kaho</firstname>
        <lastname>Poon</lastname>
        <email>kaho@gmail.com</email>
        <password>39289481fmfas@^1</password>
        <dateofbirth>1996-01-21</dateofbirth>
        <usertype>student</usertype>
    </student>
    <student>
        <firstname>Alviandy</firstname>
        <lastname>Gouw</lastname>
        <email>alviandy@gmail.com</email>
        <password>85218*2813</password>
        <dateofbirth>1998-11-03</dateofbirth>
        <usertype>student</usertype> 
    </student>
    <student>
        <firstname>Deddy</firstname>
        <lastname>Tanjaya</lastname>
        <email>deddy@gmail.com</email>
        <password>da0s94k</password>
        <dateofbirth>1998-04-21</dateofbirth>
        <usertype>student</usertype>
    </student>
</students>
