=== limyandi/TutorBooking/web/WEB-INF/tutors.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<xs:schema
 xmlns:xs="http://www.w3.org/2001/XMLSchema"
 targetNamespace="http://www.uts.edu.au/31284/wsd-tutors"
 xmlns="http://www.uts.edu.au/31284/wsd-tutors"
 elementFormDefault="qualified">
    
    <xs:simpleType name="name">
        <xs:restriction base="xs:string">
            <xs:pattern value="([A-Z][a-z]+)"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="email">
        <xs:restriction base="xs:string">
            <xs:pattern value="([A-Za-z\._]+)@(([a-z-]+)\.)+([a-z-]+)"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- Any alphanumeric characters and included some wild symbols with a minimum length of 6 and maximum length of 16.  -->
    <xs:simpleType name="password">
        <xs:restriction base="xs:string">
            <xs:pattern value="([A-Za-z0-9!@#$%^*\?]{6,16})"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="dob">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{1,2}/\d{1,2}/\d{1,4}"/>
        </xs:restriction>
    </xs:simpleType>
    
    
    <!--TODO: DO WE NEED FOR USERTYPE? -->
    <xs:simpleType name="usertype">
        <xs:restriction base="xs:string">
            <xs:pattern value="tutor"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="subject">
        <xs:restriction base="xs:string">
            <xs:pattern value="WSD|USP|SEP|AppProg|MobileApp"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!--TODO DO WE NEED FOR STATUS OF TUTOR? -->
    <xs:simpleType name="status">
        <xs:restriction base="xs:string">
            <xs:pattern value="available|unavailable"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:element name="tutors">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tutor" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="firstname" type="name"/>
                            <xs:element name="lastname" type="name"/>
                            <xs:element name="email" type="email"/>
                            <xs:element name="password" type="password"/>
                            <xs:element name="dateofbirth" type="dob"/>
                            <xs:element name="usertype" type="usertype"/>
                            <xs:element name="subject" type="subject"/>
                            <xs:element name="status" type="status"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== limyandi/TutorBooking/web/WEB-INF/tutors.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--TODO: Do we need usertype?-->
<tutors xmlns="http://www.uts.edu.au/31284/wsd-tutors"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.uts.edu.au/31284/wsd-tutors tutors.xsd">
    <tutor>
        <firstname>Rico</firstname>
        <lastname>Brilliant</lastname>
        <email>rico@gmail.com</email>
        <password>123456</password>
        <dateofbirth>09/09/1998</dateofbirth>
        <usertype>tutor</usertype>
        <subject>WSD</subject>
        <status>available</status>
    </tutor>
    <tutor>
        <firstname>Rico</firstname>
        <lastname>Brilliant</lastname>
        <email>rico@gmail.com</email>
        <password>123456</password>
        <dateofbirth>09/09/1998</dateofbirth>
        <usertype>tutor</usertype>
        <subject>USP</subject>
        <status>unavailable</status>
    </tutor>
    <tutor>
        <firstname>Rico</firstname>
        <lastname>Brilliant</lastname>
        <email>rico@gmail.com</email>
        <password>123456</password>
        <dateofbirth>09/09/1998</dateofbirth>
        <usertype>tutor</usertype>
        <subject>SEP</subject>
        <status>available</status>
    </tutor>
    <tutor>
        <firstname>Rico</firstname>
        <lastname>Brilliant</lastname>
        <email>rico@gmail.com</email>
        <password>123456</password>
        <dateofbirth>09/09/1998</dateofbirth>
        <usertype>tutor</usertype>
        <subject>AppProg</subject>
        <status>available</status>
    </tutor>
    <tutor>
        <firstname>Rico</firstname>
        <lastname>Brilliant</lastname>
        <email>rico@gmail.com</email>
        <password>123456</password>
        <dateofbirth>09/09/1998</dateofbirth>
        <usertype>tutor</usertype>
        <subject>MobileApp</subject>
        <status>available</status>
    </tutor>
</tutors>
